def ok(x):
    try:
        print(x)
    except:
        print("An exception occurred")

ok(10)